apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-hello-world
  labels:
    app: nginx-hello-world
spec:
  replicas: 3
  selector:
    matchLabels:
      app: nginx-hello-world
  template:
    metadata:
      labels:
        app: nginx-hello-world
    spec:
      containers:
        - name: nginx
          image: "image-registry.openshift-image-registry:5000/YOUR_NAMESPACE/nginx-hello-world"
          
apiVersion: project.openshift.io/v1
description: "nginx-hello-world"
displayName: nginx-hello-world
kind: ProjectRequest
metadata:
    name: nginx-hello-world
